### 1.Problem 

This course takes a coding-focused approach towards learning. In each notebook, we'll focus on solving one problem, and learn the techniques, algorithms, and data structures to devise an *efficient* solution. We will then generalize the technique and apply it to other problems.



In this notebook, we focus on solving the following problem:

> **QUESTION 1:** Alice has some cards with numbers written on them. She arranges the cards in decreasing order, and lays them out face down in a sequence on a table. She challenges Bob to pick out the card containing a given number by turning over as few cards as possible. Write a function to help Bob locate the card.

<img src="https://i.imgur.com/mazym6s.png" width="480">

This may seem like a simple problem, especially if you're familiar with the concept of _binary search_, but the strategy and technique we learning here will be widely applicable, and we'll soon use it to solve harder problems.

### 2. Come up with some example inputs & outputs. Try to cover all edge cases.

In [3]:
# query occurs in the middle
tests=[]
# test= {
#     'input': {
#         'cards': [13, 11, 10, 7, 4, 3, 1, 0],
#         'query': 1
#     }}
    
# tests.append(test)

tests.append({
    'input': {
        'cards': [13, 11, 10, 7, 4, 3, 1, 0],
        'query': 1
    },
    'output': 6
})

In [4]:
# query is the first element
tests.append({
    'input': {
        'cards': [4, 2, 1, -1],
        'query': 4
    },
    'output': 0
})

In [5]:
# query is the last element
tests.append({
    'input': {
        'cards': [3, -1, -9, -127],
        'query': -127
    },
    'output': 3
})

In [6]:
# cards contains just one element, query
tests.append({
    'input': {
        'cards': [6],
        'query': 6
    },
    'output': 0 
})

The problem statement does not specify what to do if the list `cards` does not contain the number `query`. 

1. Read the problem statement again, carefully.
2. Look through the examples provided with the problem.
3. Ask the interviewer/platform for a clarification.
4. Make a reasonable assumption, state it and move forward.

We will assume that our function will return `-1` in case `cards` does not contain `query`.

`ygdsyb`

In [7]:
tests

[{'input': {'cards': [13, 11, 10, 7, 4, 3, 1, 0], 'query': 1}, 'output': 6},
 {'input': {'cards': [4, 2, 1, -1], 'query': 4}, 'output': 0},
 {'input': {'cards': [3, -1, -9, -127], 'query': -127}, 'output': 3},
 {'input': {'cards': [6], 'query': 6}, 'output': 0}]

In [8]:
tests[1]['input']['cards']

[4, 2, 1, -1]

### 3. Come up with a correct solution for the problem
Our first goal should always be to come up with a _correct_ solution to the problem, which may necessarily be the most _efficient_ solution. The simplest or most obvious solution to a problem, which generally involves checking all possible answers is called the _brute force_ solution.

In this problem, coming up with a correct solution is quite easy: Bob can simply turn over cards in order one by one, till he find a card with the given number on it. Here's how we might implement it:

1. Create a variable `position` with the value 0.
3. Check whether the number at index `position` in `card` equals `query`.
4. If it does, `position` is the answer and can be returned from the function
5. If not, increment the value of `position` by 1, and repeat steps 2 to 5 till we reach the last position.
6. If the number was not found, return `-1`.

In [9]:
def locate_card(cards, query):
    position=0
    while True:
        if position==len(cards) :
            #return(-1)
            print('The card is not found:')
            break
        
        for card in cards:

            if card==query:
                print('The cards are:','\t',cards)
                print('The queried card is:','\t',query)
                return (position)

            else:
                position += 1
        

In [10]:
cards=tests[0]['input']['cards']
query=tests[0]['input']['query']

locate_card(cards, query)

The cards are: 	 [13, 11, 10, 7, 4, 3, 1, 0]
The queried card is: 	 1


6

In [11]:
cards=tests[1]['input']['cards']
query=tests[1]['input']['query']

locate_card(cards, query)

The cards are: 	 [4, 2, 1, -1]
The queried card is: 	 4


0

In [12]:
cards=tests[2]['input']['cards']
query=tests[2]['input']['query']

locate_card(cards, query)

The cards are: 	 [3, -1, -9, -127]
The queried card is: 	 -127


3

In [13]:
cards=tests[3]['input']['cards']
query=tests[3]['input']['query']
locate_card(cards, query)


The cards are: 	 [6]
The queried card is: 	 6


0

## For our edgy cases:

In [14]:
# cards does not contain query 
tests.append({
    'input': {
        'cards': [9, 7, 5, 2, -9],
        'query': 4
    },
    'output': -1
})

In [15]:
# cards is empty
tests.append({
    'input': {
        'cards': [],
        'query': 7
    },
    'output': -1
})

In [16]:
cards=tests[4]['input']['cards']
query=tests[4]['input']['query']
locate_card(cards, query)


The card is not found:


In [17]:
cards=tests[5]['input']['cards']
query=tests[5]['input']['query']
locate_card(cards, query)


The card is not found:


In [18]:
# numbers can repeat in cards
tests.append({
    'input': {
        'cards': [8, 8, 6, 6, 6, 6, 6, 3, 2, 2, 2, 0, 0, 0],
        'query': 3
    },
    'output': 7
})

#### So modifying our funtion a bit more:

In [19]:
import numpy as np

In [20]:
def locate_card(cards, query):
    position=0
    while True:
        if position==len(np.unique(cards)) :
            #return(-1)
            print('The card is not found:')
            break
        
        for card in np.unique(cards):

            if card==query:
                print('The cards are:','\t',cards)
                print('The queried card is:','\t',query)
                return (position)

            else:
                position += 1

In [21]:
tests

[{'input': {'cards': [13, 11, 10, 7, 4, 3, 1, 0], 'query': 1}, 'output': 6},
 {'input': {'cards': [4, 2, 1, -1], 'query': 4}, 'output': 0},
 {'input': {'cards': [3, -1, -9, -127], 'query': -127}, 'output': 3},
 {'input': {'cards': [6], 'query': 6}, 'output': 0},
 {'input': {'cards': [9, 7, 5, 2, -9], 'query': 4}, 'output': -1},
 {'input': {'cards': [], 'query': 7}, 'output': -1},
 {'input': {'cards': [8, 8, 6, 6, 6, 6, 6, 3, 2, 2, 2, 0, 0, 0], 'query': 3},
  'output': 7}]

In [22]:
cards=tests[-1]['input']['cards']
query=tests[-1]['output']
locate_card(cards, query)

The card is not found:


In [23]:
query

7

In [24]:
np.unique(cards)

array([0, 2, 3, 6, 8])

### 6. Apply the right technique to overcome the inefficiency. Repeat steps 3 to 6.

At the moment, we're simply going over cards one by one, and not even utilizing the face that they're sorted. This is called a *brute force* approach.

It would be great if Bob could somehow guess the card at the first attempt, but with all the cards turned over it's simply impossible to guess the right card. 


<img src="https://i.imgur.com/mazym6s.png" width="480">

The next best idea would be to pick a random card, and use the fact that the list is sorted, to determine whether the target card lies to the left or right of it. In fact, if we pick the middle card, we can reduce the number of additional cards to be tested to half the size of the list. Then, we can simply repeat the process with each half. This technique is called binary search. Here's a visual explanation of the technique:



<img src="https://miro.medium.com/max/494/1*3eOrsoF9idyOp-0Ll9I9PA.png" width="480">

In [25]:
def binary_search(cards, query):
    start=0
    end=len(cards)
        
    while True:
        
        mid=int((start+end)/2)
        print(start, mid,end)
        if start==end:
            if cards==query:
                print('Found the card')
                break
            else:
                print('Not Found')
                return
                break
        
        if cards[mid]==query:
            print('Found the card at position:', mid)
#             return mid
            break
        elif cards[mid]<query:
            end=mid
        else:
            start=mid+1
            
        #cards=cards[start:end]
        
            
        

In [26]:
cards=tests[1]['input']['cards']
query=tests[1]['input']['query']

binary_search(cards, query)

0 2 4
0 1 2
0 0 1
Found the card at position: 0


In [27]:
cards

[4, 2, 1, -1]

In [28]:
query

4

In [29]:
cards=tests[2]['input']['cards']
query=tests[2]['input']['query']



In [30]:
binary_search(cards, query)


0 2 4
3 3 4
Found the card at position: 3


In [31]:
cards=tests[3]['input']['cards']
query=tests[3]['input']['query']



In [32]:
binary_search(cards, query)


0 0 1
Found the card at position: 0


In [33]:
cards=tests[4]['input']['cards']
query=tests[4]['input']['query']

In [34]:
binary_search(cards, query)

0 2 5
3 4 5
3 3 4
3 3 3
Not Found


In [35]:
cards=tests[5]['input']['cards']
query=tests[5]['input']['query']

In [36]:
binary_search(cards, query)

0 0 0
Not Found


In [37]:
cards


[]

In [38]:
tests[5]

{'input': {'cards': [], 'query': 7}, 'output': -1}

In [39]:
cards=tests[6]['input']['cards']
query=tests[6]['input']['query']

In [40]:
cards

[8, 8, 6, 6, 6, 6, 6, 3, 2, 2, 2, 0, 0, 0]

In [41]:
query

3

### Making changes in the function to accommodate the last case of non unique cards:

In [42]:
import numpy as np

In [43]:
def binary_search(cards, query):
    cards=np.unique(cards)
    cards=cards[::-1]
    
    print(cards)
    start=0
    end=len(cards)
        
    while True:
        
        mid=int((start+end)/2)
        print(start, mid,end)
        if start==end:
            if cards==query:
                print('Found the card')
            else:
                print('Not Found')
                break
        
        if cards[mid]==query:
            print('Found the card at position', mid)
            #return mid
            break
        elif cards[mid]<query:
            end=mid
        else:
            start=mid+1
            
        #cards=cards[start:end]
        
            

In [44]:
cards=tests[0]['input']['cards']
query=tests[0]['input']['query']
binary_search(cards, query)


[13 11 10  7  4  3  1  0]
0 4 8
5 6 8
Found the card at position 6


In [45]:
cards

[13, 11, 10, 7, 4, 3, 1, 0]

In [46]:
query

1

In [47]:
cards=range(0,10001)
cards=cards[::-1]

In [48]:
query=np.random.randint(0,10001,1)

In [49]:
binary_search(cards, query)

[10000  9999  9998 ...     2     1     0]
0 5000 10001
0 2500 5000
0 1250 2500
0 625 1250
626 938 1250
626 782 938
626 704 782
626 665 704
666 685 704
666 675 685
666 670 675
666 668 670
669 669 670
Found the card at position 669


In [50]:
query

array([9331])

In [51]:
locate_card(cards, query)

The cards are: 	 range(10000, -1, -1)
The queried card is: 	 [9331]


9331

In [52]:
_

9331